version: "3"

services:
  #Laravel PHP
  app:
    build:
      context: ./app/laravel/
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./app/laravel:/var/www
      - ./app/etc/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      app-network:
        aliases:
          - app

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/laravel:/var/www
      - ./app/etc/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      app-network:
        aliases:
          - webserver

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    env_file: ./app/laravel/.env
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./app/etc/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      app-network:
        aliases:
          - db

#Docker Networks
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
